### PR TITLE
Minor tweaks to demo. Added Port 8080 response.

### PR DESCRIPTION
**Pull request by glfejer**
Added a new server port & some generic welcome message.
Added 'curl' to client docker file to allow application traffic check.

### CODE REVIEW

**Review by zanebeckwith — APPROVED** [review]
LGTM. Thanks!

**Review by drbild — CHANGES_REQUESTED** [review]
What happened to adding `curl` to the `enftun` image?  Here's my initial comment on that change:

"My initial reaction is to not really like adding `curl` to the `enftun` image, since it is supposed to be a minimal base image with the `enftun` software.  It's not a generic demo client.

But like `ping`, `curl` and `telnet` are helping debugging tools in network environments.  So I think I'm ok with it.
"

**Comment by glfejer** [comment]
Apparently, I had a stale `master` from which I based my branch.
@zanebeckwith already added `curl` back in April... I only noticed that when I rebased.

**Comment by zanebeckwith** [comment]
I thought I was crazy!

**Review by drbild — APPROVED** [review]
Haha, LGTM!

**Pull request merged**
